### ISSUE TITLE
Sensors appear in default room after system reboot

### ISSUE THREAD

**Issue by Heiliger85** [Zzm317/homebridge-mi-flower-mate#1]
Hi,

Thank you for your great work and the plugin.

I have 4 Sensors in my config. And the plugin will find all of them. But after the reboot the plugin lost my sensors and I must set all the sensors to their rooms again.

**Comment by Zzm317** [comment]
I will make an update to solve that later

**Comment by Zzm317** [comment]
https://github.com/Zzm317/homebridge-mi-flower-mate/commit/c6907b0576433f7390f5a1129166df3aecfdc9ac
this will not remove accessories if you reboot home bridge

**Comment by Heiliger85** [comment]
thank you
