### ISSUE TITLE
Is this for the Xiaomi Mi Flower care sensor? 

### ISSUE THREAD

**Issue by Kepete** [Zzm317/homebridge-mi-flower-mate#5]
Not and issu but more of an question to clarify. Is this plugin made for the Xiaomi Mi flower sensor. Like this one: https://www.aliexpress.com/item/Xiaomi-Mi-Flora-Monitor-Smart-Tester-Flower-Care-Soil-Water-Digital-Grass-Light-Sensor-for-Garden/32804584205.html

Or what is the Mi flower mate? 

Thanks!

**Comment by Zzm317** [comment]
mi flower mate is mi flower sensor
