### ISSUE TITLE
Let's add fertility and battery option to the plugin

### ISSUE THREAD

**Issue by Kepete** [Zzm317/homebridge-mi-flower-mate#7]
Hi, 

Thanks for the help before. I have been playing around with this for several days and I'm happy with the plugin. The are still some things that could improve even more the plugin. 
1) Fertility option. As the sensor also supports fertility information it would be a shame to not show it in homekit. 
2) Battery as a accessories option. Right now the battery is only seen in the details. Some people, including me would like to see it all the time. 

All of these things could be easily modifiable so that everyone can show what's important for them it would make this a perfect plugin. 

As I don't have any experience with writing a plugin I don't know if I can do it myself. If the developer doesn't plan to add these points I might give it a try. Any hints where to start  ? :)

**Comment by Zzm317** [comment]
If you have can contact APPLE, You can let APPLE add these things into HomeKit.
I think I have already told you that there's no Fertility in HomeKit

**Comment by Kepete** [comment]
It should be possible to make the moisture work as fertility, technically these are very similar. 
I will give it a try :)
